// src/lib/freelancers.ts

export const freelancers = [
  {
    id: 1,
    name: 'Aria Montgomery',
    skill: 'Lead UI/UX Designer',
    distance: '1.5 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'woman portrait',
    skills: ['Figma', 'UI/UX', 'Web Design', 'Mobile Apps'],
  },
  {
    id: 2,
    name: 'Ken Adams',
    skill: 'Senior Go Developer',
    distance: '0.8 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'man portrait',
    skills: ['Go', 'Docker', 'Kubernetes', 'gRPC'],
  },
  {
    id: 3,
    name: 'Lia Sharma',
    skill: 'Cloud Architect (AWS)',
    distance: '2.1 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'woman smiling',
    skills: ['AWS', 'Terraform', 'CI/CD', 'Python'],
  },
  {
    id: 4,
    name: 'David Chen',
    skill: 'Data Scientist',
    distance: '3.0 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'man glasses',
    skills: ['Python', 'TensorFlow', 'Pandas', 'SQL'],
  },
  {
    id: 5,
    name: 'Sophie Turner',
    skill: 'React Native Developer',
    distance: '1.2 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'woman red hair',
    skills: ['React Native', 'TypeScript', 'GraphQL', 'Firebase'],
  },
  {
    id: 6,
    name: 'Michael Brown',
    skill: 'Videographer & Editor',
    distance: '4.5 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'man camera',
    skills: ['Premiere Pro', 'After Effects', 'Color Grading'],
  },
  {
    id: 7,
    name: 'Emily Rodriguez',
    skill: 'Content Writer & SEO',
    distance: '2.8 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'woman writing',
    skills: ['SEO', 'Copywriting', 'Content Strategy', 'WordPress'],
  },
  {
    id: 8,
    name: 'James Wilson',
    skill: 'Full-Stack Developer',
    distance: '0.5 km',
    avatar: 'https://placehold.co/100x100.png',
    hint: 'man smiling',
    skills: ['Node.js', 'React', 'MongoDB', 'Express'],
  },
];
